@extends('errors.layout')
@section('title', 'Forbidden')
@section('code', '403')
@section('message', 'Forbidden')
@section('description', 'Akses ditolak! Anda tidak memiliki izin untuk membuka halaman atau direktori ini.')
