@extends('errors.layout')
@section('title', 'Not Found')
@section('code', '404')
@section('message', 'Not Found')
@section('description', 'Oops! Halaman yang Anda cari tidak dapat ditemukan atau mungkin telah dipindahkan.')
