@extends('errors.layout')
@section('title', 'Server Error')
@section('code', '500')
@section('message', 'Server Error')
@section('description', 'Telah terjadi kesalahan pada server internal kami. Tim teknis sedang meninjau masalah ini.')
